baseURL = 'https://testcontainers.com'
languageCode = 'en-us'
title = 'Testcontainers'

disableKinds = ['RSS']
paginate = 9999

[params]
    Description = 'Testcontainers is an opensource framework for providing lightweight, throwaway instances of common databases, Selenium web browsers, or anything else that can run in a Docker container.'
#    [params.announcement]
#        url = 'https://atomicjar.typeform.com/to/LdnwtYqF'
#        text = 'ðŸ‘‰ðŸ“‹ Community survey - tell us how you use Testcontainers and develop, test, and ship applications.'

[taxonomies]
  language = 'languages'
  tag = 'tags'
  category = 'categories'

[minify]
    minifyOutput = true

[markup]
    [markup.highlight]
        codeFences = false
    [markup.asciidocExt]
        [markup.asciidocExt.attributes]
            allow-uri-read = ""
            icons = "image"
            iconsdir = "/images/icons"
            icontype = "svg"

[sitemap]
    filename = 'sitemap.xml'

[security]
    enableInlineShortcodes = false

[security.exec]
    allow = ['^asciidoctor$']

[security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']

[module]
[[module.mounts]]
    source = 'content'
    target = 'content'
[[module.mounts]]
    source = 'static'
    target = 'static'
[[module.mounts]]
    source = 'layouts'
    target = 'layouts'
[[module.mounts]]
    source = 'data'
    target = 'data'
[[module.mounts]]
    source = 'assets'
    target = 'assets'
[[module.mounts]]
    source = 'archetypes'
    target = 'archetypes'
[[module.mounts]]
    source = 'community-module-registry/modules'
    target = 'content/modules'
[[module.mounts]]
    source = 'community-module-registry/assets'
    target = 'assets/images/modules'
[[module.mounts]]
    source = 'assets/images/modules'
    target = 'assets/images/modules'
